#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("pingpong05.Resource", IsApplication=true)]

namespace pingpong05
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int next = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pause = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int play = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int social = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int test = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int LVLInfo = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int MyButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int ScoreInfo = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int adsLayout = 2131034127;
			
			// aapt resource value: 0x7f050007
			public const int bal = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int bous01 = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int buttonL = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int buttonR = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int frameLayout1 = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int plaer = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int shareButton = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int startButton = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int tableLayout1 = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int tableLayout2 = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int tableRow1 = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int tableRow2 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
